IMPORTINGS

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

READ DATASET

In [8]:
data = pd.read_csv("Downloads/Electric_Vehicle_Population_Size_History_By_County_.csv")
data.sample(10)

,Date,County,State,Vehicle Primary Use,Battery Electric Vehicles (BEVs),Plug-In Hybrid Electric Vehicles (PHEVs),Electric Vehicle (EV) Total,Non-Electric Vehicle Total,Total Vehicles,Percent Electric Vehicles
1778,July 31 2020,Shelby,OH,Passenger,0,1,1,2,3,33.33
18915,November 30 2021,San Mateo,CA,Passenger,2,0,2,89,91,2.20
8432,October 31 2018,Lake,CA,Passenger,0,1,1,11,12,8.33
11786,September 30 2020,Williams,ND,Passenger,0,1,1,11,12,8.33
9578,January 31 2017,Juneau,AK,Passenger,0,1,1,59,60,1.67
7142,November 30 2019,Berkshire,MA,Passenger,0,1,1,5,6,16.67
5303,May 31 2022,Kern,CA,Passenger,0,1,1,197,198,0.51
10084,July 31 2021,Champaign,IL,Passenger,1,0,1,12,13,7.69
6819,December 31 2017,Howard,MD,Passenger,0,2,2,89,91,2.20
1618,January 31 2020,Suffolk,VA,Passenger,1,0,1,123,124,0.81